### ISSUE TITLE
新手开发教程

### ISSUE THREAD

**Issue by JackonYang** [pstocky/pstocky#15]
http://www.django-rest-framework.org/tutorial/quickstart/

看完 tutorial 的前 4 章。开发的过程大概是：
1. 定义 model
2. 定义 ModelSerializer。 http://www.django-rest-framework.org/api-guide/serializers/#modelserializer
3. 使用 class based views 实现基本的 增删改查操作。http://www.django-rest-framework.org/tutorial/3-class-based-views/

**Comment by NeverCc** [comment]
我该怎么创建分支啊。。。Permission to pstocky/pstocky.git denied to NeverCc.

**Comment by JackonYang** [comment]
fork，提交到自己的仓库里，然后在这个仓库里发起 pull request

**Comment by NeverCc** [comment]
看了我的了吗 = =！，提些建议。。。

**Comment by JackonYang** [comment]
你的 pull request 下，已经评论。
