### ISSUE TITLE
[需求]自动化部署

### ISSUE THREAD

**Issue by JackonYang** [pstocky/pstocky#6]
写一套可以自动生成部署配置文件的脚本。

环境包括：
- nginx
- uwsgi
- supervisor
- mysql
- redis
- celery

项目相关的配置，存储在一个配置文件中 pstock.ini
比如: 域名、mysql 的用户名／密码等。

操作流程：
1. 读取配置文件，并设置为环境变量。
2. 读取环境变量，根据 nginx 模版生成项目的 nginx 配置，并 copy 到对应的 nginx 目录下
3. ... mysql ...
   ...
4. 通过 Django 的 manage.py 执行 migration 操作，初始化数据库
5. load initial 数据
6. runserver

**Comment by rtx3** [comment]
这个是持续集成的一步，一般到正式部署才需要。操作可以靠saltstack，ansible或者fabric来实现。

**Comment by JackonYang** [comment]
@rtx3 用 docker 的一个好处就是，开发环境和正式部署保持一致。

每次更新代码的时候，都是一键更新自己的开发环境，对前端开发尤为重要。

另外，开发环境下，
mysql，redis，celery 都要用，组件也不少了。
一个一个的手动维护，也是很烦的。

工具上，比较推荐用 ansible 来做。
